// <auto-generated />
using System;
using MegaDeskRP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaDeskRP.Migrations
{
    [DbContext(typeof(MegaDeskRPContext))]
    [Migration("20190710034907_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaDeskRP.Models.Desk", b =>
                {
                    b.Property<int>("DeskId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Depth");

                    b.Property<int>("NumberOfDrawers");

                    b.Property<int>("SurfaceMaterialId");

                    b.Property<int>("Width");

                    b.HasKey("DeskId");

                    b.HasIndex("SurfaceMaterialId");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("MegaDeskRP.Models.DeskQuote", b =>
                {
                    b.Property<int>("DeskQuoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<int>("DeskId");

                    b.Property<DateTime>("QuoteDate");

                    b.Property<decimal>("QuotePrice");

                    b.Property<int>("RushOrderId");

                    b.HasKey("DeskQuoteId");

                    b.HasIndex("DeskId");

                    b.HasIndex("RushOrderId");

                    b.ToTable("DeskQuote");
                });

            modelBuilder.Entity("MegaDeskRP.Models.RushOrder", b =>
                {
                    b.Property<int>("RushOrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price1000To2000");

                    b.Property<decimal>("PriceGreater2000");

                    b.Property<decimal>("PriceLessThan1000");

                    b.Property<string>("ShippingType")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("RushOrderId");

                    b.ToTable("RushOrder");
                });

            modelBuilder.Entity("MegaDeskRP.Models.SurfaceMaterial", b =>
                {
                    b.Property<int>("SurfaceMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("MaterialPrice");

                    b.Property<string>("MaterialType");

                    b.HasKey("SurfaceMaterialId");

                    b.ToTable("SurfaceMaterial");
                });

            modelBuilder.Entity("MegaDeskRP.Models.Desk", b =>
                {
                    b.HasOne("MegaDeskRP.Models.SurfaceMaterial", "SurfaceMaterial")
                        .WithMany()
                        .HasForeignKey("SurfaceMaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MegaDeskRP.Models.DeskQuote", b =>
                {
                    b.HasOne("MegaDeskRP.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MegaDeskRP.Models.RushOrder", "RushOrder")
                        .WithMany()
                        .HasForeignKey("RushOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
